---
- name: Update APT index
  apt: update_cache=yes

- name: Remove few packages if present
  apt: pkg={{item}} state=absent
  with_items:
      - libmapserver2

- name: Install Dependencies packages
  apt: pkg={{item}} state=present
  with_items:
      - python3-pip
      - gfortran
      - libssl-dev
      - flex
      - bison
      - python3-libxml2
      - python3-lxml
      - curl
      - openssl
      - autoconf
      - apache2
      - subversion
      - git
      - python3-cssmin
      - python3-psycopg2
      - gdal-bin
      - python3-gdal
      - postgresql
      - postgis
      - r-base
      - r-cran-class
      - postgresql-{{pgvers}}-postgis-{{pgisvers}}
      - xsltproc
      - cmake
      - libapache2-mod-wsgi-py3
      - ghostscript
      - xvfb
      - python3-rpy2
      - build-essential
      - zlib1g-dev
      - libxslt1-dev
      - libxml2-dev
      - python3-dev
      - python3-setuptools
      - libcairo2-dev
      - apache2-dev
      - libproj-dev
      - libgdal-dev
      - libfreetype6-dev
      - libgeos-dev
      - libfcgi-dev
      - libmozjs185-dev
      - libssh2-1-dev
      - libfribidi-dev
      - protobuf-c-compiler
      - libprotobuf-c-dev
      - swig
      # - python-libxslt1
  register: packagesinstalled

- name: Install Python 3.x package Cheetah 3 for templates
  shell: python3 -m pip install wheel Cheetah3 rpy2 mod_wsgi 
